M48
; DRILL file {KiCad (6.0.2)} date Sun Mar 13 14:10:47 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-03-13T14:10:47-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1969
%
G90
G05
T1
X4.4488Y-5.1969
X5.2362Y-5.1969
T2
X4.8425Y-4.4882
T0
M30
